"""empty message

Revision ID: fd5ef66d9c6d
Revises: 
Create Date: 2020-01-23 18:51:05.605524

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fd5ef66d9c6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Order', sa.Column('address_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Order', 'Address', ['address_id'], ['id'], ondelete='SET NULL')
    op.drop_column('Order', 'discount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Order', sa.Column('discount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Order', type_='foreignkey')
    op.drop_column('Order', 'address_id')
    # ### end Alembic commands ###
